### ISSUE TITLE
Does not work on internal page defined in route

### ISSUE THREAD

**Issue by MehmetSert** [TypeCtrl/ngx-headroom#181]
Hello,

ngx-headroom localhost: It works fine when I open my project over 4200 and it works when I go to the internal pages from here. However, when I open an internal page, such as: localhost: 4200/test directly, it does not work.

What is the solution?

Thanks in advance.

**Comment by scttcper** [comment]
Doesn’t seem like this has anything to do with ngx headroom

**Comment by MehmetSert** [comment]
When you said this, I created and tried a new project. As you said yes, there was no problem with your plugin. I discovered that there is a problem with the "height: 100%" property of a class in my project. And the problem was solved.

Thank you.
